import { ISelectOption } from '@/types/SelectOption';

export const SKILLS_OPTIONS: ISelectOption<string>[] = [
  { key: '0', value: 'Accepting criticism', label: 'Accepting criticism' },
  { key: '1', value: 'Accountability', label: 'Accountability' },
  { key: '2', value: 'Accuracy', label: 'Accuracy' },
  { key: '3', value: 'Active learning', label: 'Active learning' },
  { key: '4', value: 'Active listening', label: 'Active listening' },
  { key: '5', value: 'Acuity', label: 'Acuity' },
  { key: '6', value: 'Adaptability', label: 'Adaptability' },
  { key: '7', value: 'Aesthetics', label: 'Aesthetics' },
  { key: '8', value: 'Analysis', label: 'Analysis' },
  { key: '9', value: 'Assertiveness', label: 'Assertiveness' },
  { key: '10', value: 'Attention to detail', label: 'Attention to detail' },
  { key: '11', value: 'Authenticity', label: 'Authenticity' },
  { key: '12', value: 'Brainstorming', label: 'Brainstorming' },
  { key: '13', value: 'Calmness', label: 'Calmness' },
  { key: '14', value: 'Charisma', label: 'Charisma' },
  { key: '15', value: 'Collaboration', label: 'Collaboration' },
  { key: '16', value: 'Commitment', label: 'Commitment' },
  { key: '17', value: 'Communication', label: 'Communication' },
  { key: '18', value: 'Confidence', label: 'Confidence' },
  { key: '19', value: 'Conflict resolution', label: 'Conflict resolution' },
  { key: '20', value: 'Constructive feedback', label: 'Constructive feedback' },
  { key: '21', value: 'Coordination', label: 'Coordination' },
  { key: '22', value: 'Creativity', label: 'Creativity' },
  { key: '23', value: 'Critical observation', label: 'Critical observation' },
  { key: '24', value: 'Critical thinking', label: 'Critical thinking' },
  { key: '25', value: 'Cultural intelligence', label: 'Cultural intelligence' },
  { key: '26', value: 'Curiosity', label: 'Curiosity' },
  { key: '27', value: 'Decision making', label: 'Decision making' },
  { key: '28', value: 'Deductive reasoning', label: 'Deductive reasoning' },
  { key: '29', value: 'Dependability', label: 'Dependability' },
  { key: '30', value: 'Depersonalization', label: 'Depersonalization' },
  { key: '31', value: 'Diplomacy', label: 'Diplomacy' },
  { key: '32', value: 'Discipline', label: 'Discipline' },
  {
    key: '33',
    value: 'Emotional intelligence',
    label: 'Emotional intelligence',
  },
  { key: '34', value: 'Empathy', label: 'Empathy' },
  { key: '35', value: 'Enthusiasm', label: 'Enthusiasm' },
  { key: '36', value: 'Experimentation', label: 'Experimentation' },
  { key: '37', value: 'Flexibility', label: 'Flexibility' },
  { key: '38', value: 'Generosity', label: 'Generosity' },
  { key: '39', value: 'Goal setting', label: 'Goal setting' },
  { key: '40', value: 'Honesty', label: 'Honesty' },
  { key: '41', value: 'Humor', label: 'Humor' },
  { key: '42', value: 'Idea exchange', label: 'Idea exchange' },
  { key: '43', value: 'Imagination', label: 'Imagination' },
  { key: '44', value: 'Innovation', label: 'Innovation' },
  { key: '45', value: 'Interpersonal', label: 'Interpersonal' },
  { key: '46', value: 'Introspection', label: 'Introspection' },
  { key: '47', value: 'Leadership', label: 'Leadership' },
  { key: '48', value: 'Listening', label: 'Listening' },
  { key: '49', value: 'Logical reasoning', label: 'Logical reasoning' },
  { key: '50', value: 'Management', label: 'Management' },
  { key: '51', value: 'Mediation', label: 'Mediation' },
  { key: '52', value: 'Mentorship', label: 'Mentorship' },
  { key: '53', value: 'Mind-mapping', label: 'Mind-mapping' },
  { key: '54', value: 'Motivation', label: 'Motivation' },
  { key: '55', value: 'Multitasking', label: 'Multitasking' },
  { key: '56', value: 'Negotiation', label: 'Negotiation' },
  { key: '57', value: 'Networking', label: 'Networking' },
  { key: '58', value: 'Observation', label: 'Observation' },
  { key: '59', value: 'Open-mindedness', label: 'Open-mindedness' },
  { key: '60', value: 'Optimism', label: 'Optimism' },
  { key: '61', value: 'Oral Communication', label: 'Oral Communication' },
  { key: '62', value: 'Organization', label: 'Organization' },
  { key: '63', value: 'Patience', label: 'Patience' },
  { key: '64', value: 'Persuasion', label: 'Persuasion' },
  { key: '65', value: 'Planning', label: 'Planning' },
  { key: '66', value: 'Positive attitude', label: 'Positive attitude' },
  { key: '67', value: 'Positivity', label: 'Positivity' },
  { key: '68', value: 'Presentation', label: 'Presentation' },
  { key: '69', value: 'Prioritizing', label: 'Prioritizing' },
  { key: '70', value: 'Problem-solving', label: 'Problem-solving' },
  { key: '71', value: 'Professionalism', label: 'Professionalism' },
  { key: '72', value: 'Project management', label: 'Project management' },
  { key: '73', value: 'Public speaking', label: 'Public speaking' },
  {
    key: '74',
    value: 'Quality client service',
    label: 'Quality client service',
  },
  { key: '75', value: 'Questioning', label: 'Questioning' },
  { key: '76', value: 'Receptive attitude', label: 'Receptive attitude' },
  { key: '77', value: 'Responsibility', label: 'Responsibility' },
  { key: '78', value: 'Scheduling', label: 'Scheduling' },
  { key: '79', value: 'Self-control', label: 'Self-control' },
  { key: '80', value: 'Self-management', label: 'Self-management' },
  { key: '81', value: 'Self-motivation', label: 'Self-motivation' },
  { key: '82', value: 'Sociability', label: 'Sociability' },
  { key: '83', value: 'Strategic thinking', label: 'Strategic thinking' },
  { key: '84', value: 'Stress management', label: 'Stress management' },
  { key: '85', value: 'System analysis', label: 'System analysis' },
  { key: '86', value: 'Taking responsibility', label: 'Taking responsibility' },
  { key: '87', value: 'Task delegation', label: 'Task delegation' },
  { key: '88', value: 'Team building', label: 'Team building' },
  { key: '89', value: 'Teamwork', label: 'Teamwork' },
  { key: '90', value: 'Technical writing', label: 'Technical writing' },
  { key: '91', value: 'Tenacity', label: 'Tenacity' },
  { key: '92', value: 'Time management', label: 'Time management' },
  { key: '93', value: 'Tolerance', label: 'Tolerance' },
  { key: '94', value: 'Verbal communication', label: 'Verbal communication' },
  { key: '95', value: 'Visual communication', label: 'Visual communication' },
  { key: '96', value: 'Willingness to learn', label: 'Willingness to learn' },
  { key: '97', value: 'Work ethic', label: 'Work ethic' },
  { key: '98', value: 'Written communication', label: 'Written communication' },
];