import { ISelectOption } from '@/types/SelectOption';
import { ERBLanguageLevel } from '@/types/Resume';

export const LANGUAGE_OPTIONS: ISelectOption<ERBLanguageLevel | null>[] = [
  {
    key: String(ERBLanguageLevel.Beginner),
    value: ERBLanguageLevel.Beginner,
    label: 'Beginner',
  },
  {
    key: String(ERBLanguageLevel.Intermediate),
    value: ERBLanguageLevel.Intermediate,
    label: 'Intermediate',
  },
  {
    key: String(ERBLanguageLevel.Advanced),
    value: ERBLanguageLevel.Advanced,
    label: 'Advanced',
  },
  {
    key: String(ERBLanguageLevel.C2),
    value: ERBLanguageLevel.C2,
    label: 'C2',
  },
  {
    key: String(ERBLanguageLevel.C1),
    value: ERBLanguageLevel.C1,
    label: 'C1',
  },
  {
    key: String(ERBLanguageLevel.B2),
    value: ERBLanguageLevel.B2,
    label: 'B2',
  },
  {
    key: String(ERBLanguageLevel.B1),
    value: ERBLanguageLevel.B1,
    label: 'B1',
  },
  {
    key: String(ERBLanguageLevel.A2),
    value: ERBLanguageLevel.A2,
    label: 'A2',
  },
  {
    key: String(ERBLanguageLevel.A1),
    value: ERBLanguageLevel.A1,
    label: 'A1',
  },
];

export const SKILLS_OPTIONS: ISelectOption<string> = [
  { id: '0', value: 'Accepting criticism', label: 'Accepting criticism' },
  { id: '1', value: 'Accountability', label: 'Accountability' },
  { id: '2', value: 'Accuracy', label: 'Accuracy' },
  { id: '3', value: 'Active learning', label: 'Active learning' },
  { id: '4', value: 'Active listening', label: 'Active listening' },
  { id: '5', value: 'Acuity', label: 'Acuity' },
  { id: '6', value: 'Adaptability', label: 'Adaptability' },
  { id: '7', value: 'Aesthetics', label: 'Aesthetics' },
  { id: '8', value: 'Analysis', label: 'Analysis' },
  { id: '9', value: 'Assertiveness', label: 'Assertiveness' },
  { id: '10', value: 'Attention to detail', label: 'Attention to detail' },
  { id: '11', value: 'Authenticity', label: 'Authenticity' },
  { id: '12', value: 'Brainstorming', label: 'Brainstorming' },
  { id: '13', value: 'Calmness', label: 'Calmness' },
  { id: '14', value: 'Charisma', label: 'Charisma' },
  { id: '15', value: 'Collaboration', label: 'Collaboration' },
  { id: '16', value: 'Commitment', label: 'Commitment' },
  { id: '17', value: 'Communication', label: 'Communication' },
  { id: '18', value: 'Confidence', label: 'Confidence' },
  { id: '19', value: 'Conflict resolution', label: 'Conflict resolution' },
  { id: '20', value: 'Constructive feedback', label: 'Constructive feedback' },
  { id: '21', value: 'Coordination', label: 'Coordination' },
  { id: '22', value: 'Creativity', label: 'Creativity' },
  { id: '23', value: 'Critical observation', label: 'Critical observation' },
  { id: '24', value: 'Critical thinking', label: 'Critical thinking' },
  { id: '25', value: 'Cultural intelligence', label: 'Cultural intelligence' },
  { id: '26', value: 'Curiosity', label: 'Curiosity' },
  { id: '27', value: 'Decision making', label: 'Decision making' },
  { id: '28', value: 'Deductive reasoning', label: 'Deductive reasoning' },
  { id: '29', value: 'Dependability', label: 'Dependability' },
  { id: '30', value: 'Depersonalization', label: 'Depersonalization' },
  { id: '31', value: 'Diplomacy', label: 'Diplomacy' },
  { id: '32', value: 'Discipline', label: 'Discipline' },
  {
    id: '33',
    value: 'Emotional intelligence',
    label: 'Emotional intelligence',
  },
  { id: '34', value: 'Empathy', label: 'Empathy' },
  { id: '35', value: 'Enthusiasm', label: 'Enthusiasm' },
  { id: '36', value: 'Experimentation', label: 'Experimentation' },
  { id: '37', value: 'Flexibility', label: 'Flexibility' },
  { id: '38', value: 'Generosity', label: 'Generosity' },
  { id: '39', value: 'Goal setting', label: 'Goal setting' },
  { id: '40', value: 'Honesty', label: 'Honesty' },
  { id: '41', value: 'Humor', label: 'Humor' },
  { id: '42', value: 'Idea exchange', label: 'Idea exchange' },
  { id: '43', value: 'Imagination', label: 'Imagination' },
  { id: '44', value: 'Innovation', label: 'Innovation' },
  { id: '45', value: 'Interpersonal', label: 'Interpersonal' },
  { id: '46', value: 'Introspection', label: 'Introspection' },
  { id: '47', value: 'Leadership', label: 'Leadership' },
  { id: '48', value: 'Listening', label: 'Listening' },
  { id: '49', value: 'Logical reasoning', label: 'Logical reasoning' },
  { id: '50', value: 'Management', label: 'Management' },
  { id: '51', value: 'Mediation', label: 'Mediation' },
  { id: '52', value: 'Mentorship', label: 'Mentorship' },
  { id: '53', value: 'Mind-mapping', label: 'Mind-mapping' },
  { id: '54', value: 'Motivation', label: 'Motivation' },
  { id: '55', value: 'Multitasking', label: 'Multitasking' },
  { id: '56', value: 'Negotiation', label: 'Negotiation' },
  { id: '57', value: 'Networking', label: 'Networking' },
  { id: '58', value: 'Observation', label: 'Observation' },
  { id: '59', value: 'Open-mindedness', label: 'Open-mindedness' },
  { id: '60', value: 'Optimism', label: 'Optimism' },
  { id: '61', value: 'Oral Communication', label: 'Oral Communication' },
  { id: '62', value: 'Organization', label: 'Organization' },
  { id: '63', value: 'Patience', label: 'Patience' },
  { id: '64', value: 'Persuasion', label: 'Persuasion' },
  { id: '65', value: 'Planning', label: 'Planning' },
  { id: '66', value: 'Positive attitude', label: 'Positive attitude' },
  { id: '67', value: 'Positivity', label: 'Positivity' },
  { id: '68', value: 'Presentation', label: 'Presentation' },
  { id: '69', value: 'Prioritizing', label: 'Prioritizing' },
  { id: '70', value: 'Problem-solving', label: 'Problem-solving' },
  { id: '71', value: 'Professionalism', label: 'Professionalism' },
  { id: '72', value: 'Project management', label: 'Project management' },
  { id: '73', value: 'Public speaking', label: 'Public speaking' },
  {
    id: '74',
    value: 'Quality client service',
    label: 'Quality client service',
  },
  { id: '75', value: 'Questioning', label: 'Questioning' },
  { id: '76', value: 'Receptive attitude', label: 'Receptive attitude' },
  { id: '77', value: 'Responsibility', label: 'Responsibility' },
  { id: '78', value: 'Scheduling', label: 'Scheduling' },
  { id: '79', value: 'Self-control', label: 'Self-control' },
  { id: '80', value: 'Self-management', label: 'Self-management' },
  { id: '81', value: 'Self-motivation', label: 'Self-motivation' },
  { id: '82', value: 'Sociability', label: 'Sociability' },
  { id: '83', value: 'Strategic thinking', label: 'Strategic thinking' },
  { id: '84', value: 'Stress management', label: 'Stress management' },
  { id: '85', value: 'System analysis', label: 'System analysis' },
  { id: '86', value: 'Taking responsibility', label: 'Taking responsibility' },
  { id: '87', value: 'Task delegation', label: 'Task delegation' },
  { id: '88', value: 'Team building', label: 'Team building' },
  { id: '89', value: 'Teamwork', label: 'Teamwork' },
  { id: '90', value: 'Technical writing', label: 'Technical writing' },
  { id: '91', value: 'Tenacity', label: 'Tenacity' },
  { id: '92', value: 'Time management', label: 'Time management' },
  { id: '93', value: 'Tolerance', label: 'Tolerance' },
  { id: '94', value: 'Verbal communication', label: 'Verbal communication' },
  { id: '95', value: 'Visual communication', label: 'Visual communication' },
  { id: '96', value: 'Willingness to learn', label: 'Willingness to learn' },
  { id: '97', value: 'Work ethic', label: 'Work ethic' },
  { id: '98', value: 'Written communication', label: 'Written communication' },
];
